# Generated by Django 5.0 on 2023-12-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
